GET http://localhost:5005/

###

GET http://localhost:5005/users

###
DELETE http://localhost:5005/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFmdGFiYWtoYW5kQGtoLmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTY5MjUyMzY2OCwiZXhwIjoxNjkyNTIzNzI4fQ.RUL25pRw9U55muhxKGrTuJg90ijHyUOnVVMygYOl6Ko
Content-Type: application/json

{
    "email": "manjunath@kh.com"
}

###
POST http://localhost:5005/signup
Content-Type: application/json

{
    "name": "aftab akhand",
    "email": "aftabakhand@kh.com",
    "password": "Aftab$1234"
}

###
POST http://localhost:5005/login
Content-Type: application/json

{
    "email": "aftabakhand@kh.com",
    "password": "Aftab$1234"
}

###
GET http://localhost:5005/profiles
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NGQ3NzQ3N2E2ZGVhOWM1MWFiYjAxNWEiLCJpYXQiOjE2OTE5MjcyMzAsImV4cCI6MTY5MTkyNzI1MH0.NKK5nE4rp_65BShbk76tbFP7SzKMNlRjyRVQcs9QCSw

###
POST http://localhost:5005/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFmdGFiYWtoYW5kQGtoLmNvbSIsImlhdCI6MTY5MjUyMzUwMCwiZXhwIjoxNjkyNTI0MTAwfQ.ERp7vgmH_xeqA9LBn83NaP2sW868Ifj4lhCRCjNTdkc"
}

###
POST http://localhost:5005/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NGQ3NzQ3N2E2ZGVhOWM1MWFiYjAxNWEiLCJpYXQiOjE2OTE5MjczMjYsImV4cCI6MTY5MTkyNzQ0Nn0.xG8le_ntlJHfnwqw6L7_gEFGvDWXxznoQddbaWD8kFE"
}

# ###
# POST http://localhost:5005/profiles

###
GET http://localhost:5005/customers

###
GET http://localhost:5005/accounts

###
POST http://localhost:5005/admin
Content-Type: application/json
Authorization: Bearer MASTER_TOKEN_FOR_MY_APP

{
    "email": "aftabakhand@kh.com"
}