GET http://localhost:5007/listings

###

GET http://localhost:5007/test

###

GET http://localhost:5007/listings/64cf74bfc2dc4eccd6256301

###

POST http://localhost:5007/listings
Content-Type: application/json

{
    "name": "Saurab home stays",
    "price": 1700,
    "description": "very good home stay with delicious breakfast",
    "currency": "INR"
}

###

PUT http://localhost:5007/listings/64cf74bfc2dc4eccd6256301
Content-Type: application/json

{
    "name": "Chanda home stays",
    "description": "brillant home stay with delicious breakfast",
    "currency": "INR"
}

###

PATCH http://localhost:5007/listings/64cf74bfc2dc4eccd6256301
Content-Type: application/json

{
    "price": 2800
}

###
DELETE http://localhost:5007/listings/64cf74bfc2dc4eccd6256301